name: emissioneval
channels:
- conda-forge
- defaults
dependencies:
- arrow=0.12.*
- branca=0.3.*
- folium=0.8.*
- geojson=2.3.*
- ipython=5.3.*
- jupyter=1.0.*
- matplotlib
- pandas=0.20.*
- pip=9.0.*
- python=3.6.*
- requests=2.22.*
- shapely=1.6.*
- pip:
    - osmapi==1.2.*
    - polyline==1.3.*
