name: emissioneval
channels:
- conda-forge
dependencies:
- arrow=1.2.3


- matplotlib=3.7.1
- pandas=1.5.3
- pip=23.0
- requests=2.28.2
- scipy=1.10.0
- shapely=2.0.1
- geopandas=0.12.2
- pip:
    - osmapi==3.1.0
    - polyline==2.0.0
    - anytree==2.8.0
    - utm==0.7.0
    - branca==0.6.0
    - folium==0.14.0
    - geojson==3.0.1
