name: emissioneval
channels:
- conda-forge
dependencies:
- arrow=0.13.1
- matplotlib=3.1.3
- pandas=1.0.3
- pip=20.0.2
- requests=2.23.0
- scipy=1.4.1
- shapely=1.6.4
- geopandas=0.6.1
- pip:
    - osmapi==1.2.*
    - polyline==1.3.*
    - anytree==2.6.*
    - utm==0.5.*
    - branca==0.3.*
    - folium==0.8.*
    - geojson==2.3.*
